// functions/mcp.ts
//
// Remote MCP server for know.2nth.ai — Phase 0 (read-only, public, no auth).
//
// A minimal, stateless Model Context Protocol server over Streamable HTTP,
// implemented as a Cloudflare Pages Function so it deploys with the site.
// Speaks JSON-RPC 2.0 on POST /mcp and returns a single JSON response per
// request (the spec permits application/json for non-streaming servers).
//
// Tools:
//   search_tree(query, limit?) — keyword search across the knowledge tree
//   list_domains()             — the domains and how many live leaves each has
//   get_leaf(path)             — clean markdown of one explainer leaf
//
// Data:
//   /agent-index.json  (committed, generated by scripts/gen-agent-index.mjs)
//   /api/context/<path> (the existing agent-fetch Function, reused for get_leaf)
//
// Discover from Claude (custom connector / Connectors Directory) or ChatGPT
// (Developer Mode) by pointing them at https://know.2nth.ai/mcp.
//
// Phase 1+ will add semantic search (AutoRAG/Vectorize), auth (OAuth), and
// member/partner-scoped tools. This file stays deliberately small.

interface Env {
  ASSETS: Fetcher;
}

const SERVER = { name: 'know.2nth.ai', version: '0.1.0' };
const DEFAULT_PROTOCOL = '2025-06-18';

const cors: Record<string, string> = {
  'access-control-allow-origin': '*',
  'access-control-allow-methods': 'GET, POST, OPTIONS',
  'access-control-allow-headers': 'content-type, accept, authorization, mcp-protocol-version, mcp-session-id',
  'access-control-expose-headers': 'mcp-session-id',
};

const TOOLS = [
  {
    name: 'search_tree',
    description:
      'Search the know.2nth.ai knowledge tree by keyword. Returns matching leaves and CEO briefings with their title, domain, a one-line description, and how to fetch the full text. Use this first to find the right leaf, then call get_leaf.',
    inputSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Keywords to search for, e.g. "dataverse alm" or "open weight residency".' },
        limit: { type: 'number', description: 'Max results (default 8, max 25).' },
      },
      required: ['query'],
    },
  },
  {
    name: 'list_domains',
    description:
      'List the top-level domains of the knowledge tree (agents, software, tech, data, biz, …) with a live-leaf count and the hub URL for each. Use this to orient before searching.',
    inputSchema: { type: 'object', properties: {} },
  },
  {
    name: 'get_leaf',
    description:
      'Fetch the full text of one explainer leaf as clean agent-markdown. Pass the leaf path exactly as returned by search_tree, e.g. "agents/glm" or "tech/microsoft/dataverse". (CEO briefings are the plain-language layer — fetch those by their URL from search_tree.)',
    inputSchema: {
      type: 'object',
      properties: {
        path: { type: 'string', description: 'Leaf path, e.g. "software/orchestrating-agents".' },
      },
      required: ['path'],
    },
  },
];

// ---------------------------------------------------------------------------
// HTTP layer
// ---------------------------------------------------------------------------

export const onRequestOptions: PagesFunction<Env> = async () =>
  new Response(null, { status: 204, headers: cors });

export const onRequestGet: PagesFunction<Env> = async ({ request }) => {
  // Streamable HTTP uses GET only to open a server→client SSE stream. This
  // server has no server-initiated messages, so per spec we return 405 to an
  // SSE probe. A plain browser gets a short human/agent description instead.
  const accept = request.headers.get('accept') || '';
  if (accept.includes('text/event-stream')) {
    return new Response('This MCP server does not offer an SSE stream. POST JSON-RPC to /mcp.', {
      status: 405,
      headers: { 'content-type': 'text/plain; charset=utf-8', allow: 'POST, OPTIONS', ...cors },
    });
  }
  const info =
    `know.2nth.ai — remote MCP server (Phase 0)\n\n` +
    `Transport: Streamable HTTP (POST JSON-RPC 2.0 to this URL).\n` +
    `Tools: ${TOOLS.map((t) => t.name).join(', ')}.\n\n` +
    `Add as a custom connector in Claude, or in ChatGPT Developer Mode, using: https://know.2nth.ai/mcp\n` +
    `Human site: https://know.2nth.ai · Plain-text index: https://know.2nth.ai/llms.txt\n`;
  return new Response(info, { status: 200, headers: { 'content-type': 'text/plain; charset=utf-8', ...cors } });
};

export const onRequestPost: PagesFunction<Env> = async ({ request, env }) => {
  let payload: unknown;
  try {
    payload = await request.json();
  } catch {
    return jsonRpcError(null, -32700, 'Parse error');
  }

  const origin = new URL(request.url).origin;
  const batch = Array.isArray(payload) ? payload : [payload];
  const responses: unknown[] = [];

  for (const msg of batch) {
    const m = msg as JsonRpcRequest;
    // Notifications (no id) get no response body.
    if (m == null || m.id === undefined || m.id === null) continue;
    responses.push(await handle(m, env, origin));
  }

  // A POST of only notifications → 202 Accepted, empty body.
  if (responses.length === 0) return new Response(null, { status: 202, headers: cors });

  const body = Array.isArray(payload) ? responses : responses[0];
  return new Response(JSON.stringify(body), {
    status: 200,
    headers: { 'content-type': 'application/json', ...cors },
  });
};

interface JsonRpcRequest {
  jsonrpc?: string;
  id?: string | number | null;
  method?: string;
  params?: Record<string, unknown>;
}

async function handle(req: JsonRpcRequest, env: Env, origin: string): Promise<unknown> {
  const { id, method, params } = req;
  try {
    switch (method) {
      case 'initialize':
        return ok(id, {
          protocolVersion: (params?.protocolVersion as string) || DEFAULT_PROTOCOL,
          capabilities: { tools: { listChanged: false } },
          serverInfo: SERVER,
          instructions:
            'know.2nth.ai is a knowledge tree of technology explainer "leaves" and plain-language CEO briefings, with a South African delivery slant. Use search_tree to find a topic, then get_leaf to read it.',
        });
      case 'ping':
        return ok(id, {});
      case 'tools/list':
        return ok(id, { tools: TOOLS });
      case 'tools/call': {
        const name = params?.name as string;
        const args = (params?.arguments as Record<string, unknown>) || {};
        const text = await callTool(name, args, env, origin);
        return ok(id, { content: [{ type: 'text', text }], isError: false });
      }
      default:
        return err(id, -32601, `Method not found: ${method}`);
    }
  } catch (e) {
    return err(id, -32603, `Internal error: ${(e as Error).message}`);
  }
}

// ---------------------------------------------------------------------------
// Tools
// ---------------------------------------------------------------------------

interface IndexItem {
  title: string;
  description: string;
  domain: string;
  kind: 'hub' | 'leaf' | 'briefing';
  url: string;
  fetch: string | null;
}

async function loadIndex(env: Env, origin: string): Promise<IndexItem[]> {
  const r = await env.ASSETS.fetch(new Request(new URL('/agent-index.json', origin).toString()));
  if (!r.ok) throw new Error('index unavailable');
  const j = (await r.json()) as { items: IndexItem[] };
  return j.items;
}

async function callTool(name: string, args: Record<string, unknown>, env: Env, origin: string): Promise<string> {
  switch (name) {
    case 'search_tree': {
      const query = String(args.query || '').trim();
      if (!query) return 'Provide a "query" to search for.';
      const limit = Math.min(Math.max(Number(args.limit) || 8, 1), 25);
      const items = await loadIndex(env, origin);
      const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
      const scored = items
        .map((it) => {
          const title = it.title.toLowerCase();
          const desc = it.description.toLowerCase();
          const dom = it.domain.toLowerCase();
          let score = 0;
          for (const t of terms) {
            if (title.includes(t)) score += 3;
            if (dom.includes(t)) score += 2;
            if (desc.includes(t)) score += 1;
          }
          return { it, score };
        })
        .filter((s) => s.score > 0)
        .sort((a, b) => b.score - a.score)
        .slice(0, limit);

      if (scored.length === 0) return `No matches for "${query}". Try broader keywords, or call list_domains.`;

      const lines = [`Found ${scored.length} result(s) for "${query}":\n`];
      for (const { it } of scored) {
        const how = it.fetch ? `get_leaf path: ${it.fetch}` : `fetch by URL (briefing)`;
        lines.push(
          `- **${cleanTitle(it.title)}** — ${it.domain} · ${it.kind}\n  ${it.description}\n  ${it.url}\n  ${how}`,
        );
      }
      return lines.join('\n');
    }

    case 'list_domains': {
      const items = await loadIndex(env, origin);
      const map = new Map<string, { leaves: number; hub?: string }>();
      for (const it of items) {
        if (!map.has(it.domain)) map.set(it.domain, { leaves: 0 });
        const e = map.get(it.domain)!;
        if (it.kind === 'leaf') e.leaves += 1;
        if (it.kind === 'hub') {
          // Prefer the domain-root hub (fetch === domain); fall back to any sub-hub.
          if (it.fetch === it.domain) e.hub = it.url;
          else if (!e.hub) e.hub = it.url;
        }
      }
      const rows = [...map.entries()].sort((a, b) => b[1].leaves - a[1].leaves);
      const lines = ['Knowledge-tree domains (by live-leaf count):\n'];
      for (const [domain, e] of rows) {
        lines.push(`- **${domain}** — ${e.leaves} leaves${e.hub ? `\n  ${e.hub}` : ''}`);
      }
      lines.push('\nUse search_tree(query) to find a topic, then get_leaf(path) to read it.');
      return lines.join('\n');
    }

    case 'get_leaf': {
      let path = String(args.path || '').trim();
      if (!path) return 'Provide a "path", e.g. "agents/glm".';
      path = path
        .replace(/^https?:\/\/[^/]+/i, '')
        .replace(/^\/+/, '')
        .replace(/^api\/context\//, '')
        .replace(/^explainers\//, '')
        .replace(/\.html$/, '')
        .replace(/\/+$/, '');
      const r = await fetch(new URL(`/api/context/${path}`, origin).toString(), {
        headers: { accept: 'text/markdown' },
      });
      if (!r.ok) {
        return `No explainer leaf at "${path}" (status ${r.status}). Use search_tree to find valid paths. If this is a CEO briefing, open its URL directly.`;
      }
      return await r.text();
    }

    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}

function cleanTitle(t: string): string {
  return t.replace(/\s*(—|·|&mdash;|\|)\s*know\.2nth\.ai.*$/i, '').trim() || t;
}

// ---------------------------------------------------------------------------
// JSON-RPC helpers
// ---------------------------------------------------------------------------

function ok(id: unknown, result: unknown) {
  return { jsonrpc: '2.0', id, result };
}
function err(id: unknown, code: number, message: string) {
  return { jsonrpc: '2.0', id, error: { code, message } };
}
function jsonRpcError(id: unknown, code: number, message: string): Response {
  return new Response(JSON.stringify(err(id, code, message)), {
    status: 200,
    headers: { 'content-type': 'application/json', ...cors },
  });
}
